"use client";

import "./css/style.css";

import { Inter, Caveat } from "next/font/google";
import localFont from "next/font/local";
import Theme from "./theme-provider";
import Header from "@/components/ui/header";
import { Toaster } from "sonner";
import { NextUIProvider } from "@nextui-org/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-caveat",
  display: "swap",
});

const orbiter = localFont({
  src: [
    {
      path: "../public/fonts/OrbiterDisplay-Bold.woff",
      weight: "700",
    },
  ],
  variable: "--font-orbiter",
  display: "swap",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* suppressHydrationWarning: https://github.com/vercel/next.js/issues/44343 */}
      <body
        className={`${inter.variable} ${caveat.variable} ${orbiter.variable} font-inter antialiased bg-white text-slate-800 dark:bg-slate-950 dark:text-slate-200 tracking-tight`}
      >
        <NextUIProvider>
          <Theme>
            <Header />
            <main className="max-w-xl lg:max-w-[calc(50%+theme(maxWidth.xl))] mx-auto px-4 sm:px-6 pt-16">
              {children}
            </main>
          </Theme>
          <Toaster />
        </NextUIProvider>
      </body>
    </html>
  );
}
